export const demoBookings = [
  {
    id: 'FYF-1024',
    status: 'new',
    createdAt: '2026-08-27T14:20:00.000Z',
    updatedAt: '2026-08-27T14:20:00.000Z',
    name: 'Jordan Miller',
    email: 'jordan@example.com',
    phone: '(555) 555-1212',
    occasion: 'Birthday',
    eventDate: '2026-09-12',
    setupWindow: 'Evening before',
    serviceArea: 'West Loop',
    honoreeName: 'Jordan',
    displayMessage: 'Happy 30th Jordan',
    themeNotes: 'Bold color, stars, and a clean modern look.',
    builderLayout: {
      version: 1,
      createdAt: '2026-08-27T14:18:00.000Z',
      summary: '3 pieces: 2 letters, 1 number.',
      pieces: [
        {
          id: 'happy',
          instanceId: 'demo-happy',
          label: 'HAPPY',
          category: 'letter',
          color: '#123526',
          textColor: '#fffdf8',
          shape: 'rectangle',
          x: 18,
          y: 30,
          rotation: -3,
          scale: 1,
        },
        {
          id: 'birthday',
          instanceId: 'demo-birthday',
          label: 'BIRTHDAY',
          category: 'letter',
          color: '#f26b5b',
          textColor: '#fffdf8',
          shape: 'rectangle',
          x: 44,
          y: 30,
          rotation: 2,
          scale: 1,
        },
        {
          id: 'age',
          instanceId: 'demo-age',
          label: '30',
          category: 'number',
          color: '#f7d56f',
          textColor: '#17211b',
          shape: 'circle',
          x: 67,
          y: 50,
          rotation: 5,
          scale: 1.18,
        },
      ],
    },  },
  {
    id: 'FYF-1023',
    status: 'reviewing',
    createdAt: '2026-08-26T19:42:00.000Z',
    updatedAt: '2026-08-27T09:15:00.000Z',
    name: 'Avery Chen',
    email: 'avery@example.com',
    phone: '(555) 555-3434',
    occasion: 'New baby',
    eventDate: '2026-09-18',
    setupWindow: 'Morning of event',
    serviceArea: 'Oak Park',
    honoreeName: 'Noah',
    displayMessage: 'Welcome Home Baby Noah',
    themeNotes: 'Soft greens, cream, and simple baby icons.',
  },
  {
    id: 'FYF-1022',
    status: 'confirmed',
    createdAt: '2026-08-24T16:30:00.000Z',
    updatedAt: '2026-08-25T12:10:00.000Z',
    name: 'Morgan Davis',
    email: 'morgan@example.com',
    phone: '(555) 555-6767',
    occasion: 'Graduation',
    eventDate: '2026-09-21',
    setupWindow: 'Afternoon of event',
    serviceArea: 'Naperville',
    honoreeName: 'Ava',
    displayMessage: 'Congrats Ava Class of 2027',
    themeNotes: 'Blue and silver school colors with class year numbers.',
  },
  {
    id: 'FYF-1021',
    status: 'completed',
    createdAt: '2026-08-12T10:05:00.000Z',
    updatedAt: '2026-08-22T20:40:00.000Z',
    name: 'Sam Rivera',
    email: 'sam@example.com',
    phone: '(555) 555-9090',
    occasion: 'Retirement',
    eventDate: '2026-08-22',
    setupWindow: 'Morning of event',
    serviceArea: 'Elmhurst',
    honoreeName: 'Sam',
    displayMessage: 'Happy Retirement Sam',
    themeNotes: 'Classic, polished, and not too playful.',
  },
];
